default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USER'] || 'uczelnia123' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'uczelnia123' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: uczelnia
